### ISSUE TITLE
How it runs?

### ISSUE THREAD

**Issue by stargame25** [zyberspace/php-steam-web-api-client#1]
I mean i don't understand how to run it, and how it's works at all.

**Comment by Dierme** [comment]
There is a simple example how you can use it
`<?php
/**
 * Created by PhpStorm.
 * User: kalim_000
 * Date: 1/10/2017
 * Time: 2:53 PM
 */

namespace backend\app;


class ApiClient{

    public $steamID;
    private $client;
    private $connection;


    public function __construct($steamID){
        $this->steamID = $steamID;
        $this->client = SteamWebApiClientWrapper::getInstance();
        $this->connection = \Yii::$app->db;
    }

    public function getCurrentStatCSGO(){
        $steamUserStats = new \Zyberspace\SteamWebApi\Interfaces\ISteamUserStats($this->client);
        $userStats = $steamUserStats->GetUserStatsForGameV2($this->steamID,730);
        $this->insertStats($userStats->playerstats->stats);
    }

    private function insertStats($userStats){

        $statColNames = array();
        $statColValues = array();

        $statColNames[] = 'steam_id';
        $statColNames[] = 'date_added';
        $statColValues[] = '\''.$this->steamID.'\'';
        $statColValues[] = '\''.date("Y-m-d H:i:s").'\'';
        foreach ($userStats as $statObject){
            if(!$this->filterStatName($statObject->name)){
                continue;
            }
            $statColNames[] = $statObject->name;
            $statColValues[] = '\''.$statObject->value.'\'';
        }

        $statColNames = implode(',', $statColNames);
        $statColValues = implode(',', $statColValues);

        $sql = "INSERT INTO CSGO_CLIENT_STATS($statColNames) VALUE($statColValues)";

        $statement = $this->connection->createCommand($sql);

        $statement->execute();
    }

    private function filterStatName($statName){
        /*
         * checks that stat name does not contain comas
         * WHY: there are stat names like GI.lesson.csgo_instr_explain_buymenu
         * PDO thinks of it like separated DB namespace
         * Those attr does not contain any particular value, so they are just excluded from table
         */
        if(strpos($statName, '.') !== false){
            return false;
        }
        return true;
    }

}`

**Comment by stargame25** [comment]
Ok, ty but also don't understand where i need to write information i mean like a STEAM API Key and STEAM ID

**Comment by zyberspace** [comment]
Hi, you already have a simple example in the README of the project:
```php
require('vendor/autoload.php');

$client = new \Zyberspace\SteamWebApi\Client($_ENV['STEAM_WEB_API_KEY']);
$steamUser = new \Zyberspace\SteamWebApi\Interfaces\ISteamUser($client);
$response = $steamUser->GetPlayerSummariesV2(implode(',', $steamIds));

var_dump($response);
```

In this example the steam api key comes from the command line environment. For example:  
`STEAM_WEB_API_KEY=zuwbnciqwba!Ndsudas php myscript.php`

In production you would probably write the api key to a config file which doesn't get tracked by your vcs (add the filename to  `.gitignore` for git).

For example the [interface generator](https://github.com/zyberspace/php-steam-web-api-client/blob/master/lib/Zyberspace/SteamWebApi/InterfaceGenerator.php#L20-L36) used in this project first checks if he got the api key as an argument and otherwise tries to load it from an `.apikey` file.
```php
    static protected function _getApiKey(Event $event) {
        //Check if api key got passed as argument
        $arguments = $event->getArguments();
        if (isset($arguments[0])) {
            return $arguments[0];
        }
        //Check for `.apikey` file in the working directory
        $composer = $event->getComposer();
        $apiKeyFile = realpath(implode(DIRECTORY_SEPARATOR, [__DIR__, '..', '..', '..', '.apikey']));
        if (is_readable($apiKeyFile)) {
            return trim(file_get_contents($apiKeyFile));
        }
        //No api key found, throw Exception
        throw new \Exception('Please provide a valid api key. Pass it as argument or put it in the `.apikey` file.');
    }
```

-----------------------------------------------------------------------------------------------------------

Regarding the steam id, you don't need your own steam id, the api key is enough.  
For information about other users a database is usually the best place to store data like this if it changes frequently. If you **always** query the same users, just put them into a json file that preferably doesn't get tracked by git either.

**Comment by stargame25** [comment]
Thanks
